name: Build

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]

permissions:
  contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest


          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          PASSWORD: ${{ secrets.PASSWORD }}
